add_generate_public_private_methods
unurgunite/advanced_code_generator pull request #1
Opened 2024-05-02 12:19 UTC by o-200

2024-05-10 10:45 UTC, unurgunite requested changes

2024-05-10 10:45 UTC, unurgunite commented on lib/code_generator/generator.rb
> +    def generate_public_private_methods
There was a mistake from my side. I mixed up method names in a hurry. We should add a generator(s) for private methods and private class methods, not for public private methods (it's impossible anyway in Ruby and confuses all of OOP rules). I found and corrected typo in README. My bad... Correct TODO is: https://github.com/unurgunite/code_generator/tree/development?tab=readme-ov-file#todo

2024-05-22 12:56 UTC, o-200 commented
hey, i didnt forgot about your request so im in working on that pull request. Wait for that week for results :+1:

2024-05-24 08:35 UTC, unurgunite commented
Good, now there also should be a signature for method: sig/code_generator/generator.rbs

2025-11-06 18:31 UTC, unurgunite commented
Closed due to the lack of need for this code implementation (More info in #2)

2025-11-06 18:31 UTC, closed without merging